project_id = "wpewsxohwwvdrinowxjb"

[functions.generate-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.license-check]
verify_jwt = false

[functions.license-remind]
verify_jwt = false
